version: "3.5"

services:
  apache-php:
    build:
      ./php
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: library/mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: framework_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
    - 8081:80
